/* eslint-disable */
// REBASE-based internal restriction enzyme database
// Source: REBASE (Roberts et al.), curated subset of 230+ Type II enzymes

export type Overhang = '5prime' | '3prime' | 'blunt';
export type EnzymeType = 'II' | 'IIS' | 'IIP';

export interface RestrictionEnzyme {
  name: string;
  recognitionSeq: string; // IUPAC, 5'→3' on top strand
  cutPos: number;         // 0-indexed cut position on top strand within recognition seq
  cutPosBottom: number;   // 0-indexed cut position on bottom strand
  overhang: Overhang;
  methylationSensitive: boolean;
  suppliers: string[];
  type: EnzymeType;
}

export const REBASE_ENZYMES: RestrictionEnzyme[] = [
  // ─── Classic 6-cutters ──────────────────────────────────────────────
  { name:'EcoRI',   recognitionSeq:'GAATTC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'BamHI',   recognitionSeq:'GGATCC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'HindIII', recognitionSeq:'AAGCTT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'SalI',    recognitionSeq:'GTCGAC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'XhoI',    recognitionSeq:'CTCGAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'KpnI',    recognitionSeq:'GGTACC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SacI',    recognitionSeq:'GAGCTC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'NheI',    recognitionSeq:'GCTAGC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'XbaI',    recognitionSeq:'TCTAGA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SpeI',    recognitionSeq:'ACTAGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'SphI',    recognitionSeq:'GCATGC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'PstI',    recognitionSeq:'CTGCAG', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'ClaI',    recognitionSeq:'ATCGAT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'BglII',   recognitionSeq:'AGATCT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'MluI',    recognitionSeq:'ACGCGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'NcoI',    recognitionSeq:'CCATGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'NdeI',    recognitionSeq:'CATATG', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NotI',    recognitionSeq:'GCGGCCGC', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],        type:'II' },
  { name:'AscI',    recognitionSeq:'GGCGCGCC', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'PacI',    recognitionSeq:'TTAATTAA', cutPos:3, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'SwaI',    recognitionSeq:'ATTTAAAT', cutPos:4, cutPosBottom:4, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'FseI',    recognitionSeq:'GGCCGGCC', cutPos:6, cutPosBottom:2, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'SfiI',    recognitionSeq:'GGCCNNNNNGGCC', cutPos:8, cutPosBottom:13, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo'],           type:'IIP' },
  { name:'ApaI',    recognitionSeq:'GGGCCC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'AvaI',    recognitionSeq:'CYCGRG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'ScaI',    recognitionSeq:'AGTACT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'StuI',    recognitionSeq:'AGGCCT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NarI',    recognitionSeq:'GGCGCC', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'SacII',   recognitionSeq:'CCGCGG', cutPos:4, cutPosBottom:2, overhang:'3prime', methylationSensitive:true,  suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'MfeI',    recognitionSeq:'CAATTG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AclI',    recognitionSeq:'AACGTT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AfeI',    recognitionSeq:'AGCGCT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AgeI',    recognitionSeq:'ACCGGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'AhdI',    recognitionSeq:'GACNNNNNGTC', cutPos:6, cutPosBottom:5, overhang:'blunt', methylationSensitive:false, suppliers:['NEB'],                        type:'II' },
  { name:'AloI',    recognitionSeq:'GAACNNNNNNTCC', cutPos:7, cutPosBottom:12, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                 type:'IIS' },
  { name:'ApaLI',   recognitionSeq:'GTGCAC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'ApoI',    recognitionSeq:'RAATTY', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AscI',    recognitionSeq:'GGCGCGCC', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'AseI',    recognitionSeq:'ATTAAT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AsiSI',   recognitionSeq:'GCGATCGC', cutPos:5, cutPosBottom:3, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'AvrII',   recognitionSeq:'CCTAGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  // ─── 4-cutters ──────────────────────────────────────────────────────
  { name:'MboI',    recognitionSeq:'GATC',   cutPos:0, cutPosBottom:4, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'Sau3AI',  recognitionSeq:'GATC',   cutPos:0, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'TaqI',    recognitionSeq:'TCGA',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'HaeIII',  recognitionSeq:'GGCC',   cutPos:2, cutPosBottom:2, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'AluI',    recognitionSeq:'AGCT',   cutPos:2, cutPosBottom:2, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'MspI',    recognitionSeq:'CCGG',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'HpaII',   recognitionSeq:'CCGG',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'DpnI',    recognitionSeq:'GATC',   cutPos:2, cutPosBottom:2, overhang:'blunt',  methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'CfoI',    recognitionSeq:'GCGC',   cutPos:3, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'HinfI',   recognitionSeq:'GANTC',  cutPos:1, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'MaeII',   recognitionSeq:'ACGT',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'NlaIII',  recognitionSeq:'CATG',   cutPos:4, cutPosBottom:0, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'RsaI',    recognitionSeq:'GTAC',   cutPos:2, cutPosBottom:2, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'CviAII',  recognitionSeq:'CATG',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  // ─── 5-cutters ──────────────────────────────────────────────────────
  { name:'EcoRV',   recognitionSeq:'GATATC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'PvuII',   recognitionSeq:'CAGCTG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SmaI',    recognitionSeq:'CCCGGG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'XmaI',    recognitionSeq:'CCCGGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BstEII',  recognitionSeq:'GGTNACC', cutPos:1, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                           type:'II' },
  { name:'SalI',    recognitionSeq:'GTCGAC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'HincII',  recognitionSeq:'GTYRAC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PvuI',    recognitionSeq:'CGATCG', cutPos:4, cutPosBottom:2, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'ClaI',    recognitionSeq:'ATCGAT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  // ─── Type IIS (offset cutters, commonly used in Golden Gate) ────────
  { name:'BsaI',    recognitionSeq:'GGTCTC', cutPos:7, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                  type:'IIS' },
  { name:'BbsI',    recognitionSeq:'GAAGAC', cutPos:8, cutPosBottom:12, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                           type:'IIS' },
  { name:'BsmBI',   recognitionSeq:'CGTCTC', cutPos:7, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                  type:'IIS' },
  { name:'SapI',    recognitionSeq:'GCTCTTC', cutPos:8, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BtgZI',   recognitionSeq:'GCGATG', cutPos:10, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'Esp3I',   recognitionSeq:'CGTCTC', cutPos:7, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                        type:'IIS' },
  { name:'BseYI',   recognitionSeq:'CCCAGC', cutPos:10, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BsmBI',   recognitionSeq:'CGTCTC', cutPos:7, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                           type:'IIS' },
  { name:'BtgZI',   recognitionSeq:'GCGATG', cutPos:10, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'LguI',    recognitionSeq:'GCTCTTC', cutPos:8, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                       type:'IIS' },
  { name:'BpiI',    recognitionSeq:'GAAGAC', cutPos:8, cutPosBottom:12, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                        type:'IIS' },
  { name:'BpuEI',   recognitionSeq:'CTTGAAG', cutPos:16, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                         type:'IIS' },
  { name:'BsgI',    recognitionSeq:'GTGCAG', cutPos:22, cutPosBottom:20, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BspQI',   recognitionSeq:'GCTCTTC', cutPos:8, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BsrDI',   recognitionSeq:'GCAATG', cutPos:8, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'IIS' },
  { name:'BtgZI',   recognitionSeq:'GCGATG', cutPos:10, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  // ─── Rare cutters / 8-cutters ───────────────────────────────────────
  { name:'SrfI',    recognitionSeq:'GCCCGGGC', cutPos:4, cutPosBottom:4, overhang:'blunt',  methylationSensitive:false, suppliers:['Stratagene'],                    type:'II' },
  { name:'I-SceI',  recognitionSeq:'TAGGGATAACAGGGTAAT', cutPos:9, cutPosBottom:9, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                 type:'II' },
  // ─── Additional common enzymes ───────────────────────────────────────
  { name:'AccI',    recognitionSeq:'GTYRAC', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                          type:'II' },
  { name:'AccIII',  recognitionSeq:'TCCGGA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                          type:'II' },
  { name:'AciI',    recognitionSeq:'CCGC',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'AflII',   recognitionSeq:'CTTAAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'AflIII',  recognitionSeq:'ACRYGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AgeI',    recognitionSeq:'ACCGGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'AhdI',    recognitionSeq:'GACNNNNNGTC', cutPos:6, cutPosBottom:5, overhang:'blunt', methylationSensitive:false, suppliers:['NEB'],                        type:'II' },
  { name:'AleI',    recognitionSeq:'CACNNNNGTG', cutPos:5, cutPosBottom:5, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                        type:'II' },
  { name:'AlwNI',   recognitionSeq:'CAGNNNCTG', cutPos:6, cutPosBottom:3, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                         type:'II' },
  { name:'ApaLI',   recognitionSeq:'GTGCAC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'ApoI',    recognitionSeq:'RAATTY', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AscI',    recognitionSeq:'GGCGCGCC', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'AseI',    recognitionSeq:'ATTAAT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'AvrII',   recognitionSeq:'CCTAGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BaeI',    recognitionSeq:'NNNNNNNNNNNNNNNNNNN', cutPos:10, cutPosBottom:15, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],               type:'IIS' },
  { name:'BamHI',   recognitionSeq:'GGATCC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'BclI',    recognitionSeq:'TGATCA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'BfaI',    recognitionSeq:'CTAG',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BglI',    recognitionSeq:'GCCNNNNNGGC', cutPos:7, cutPosBottom:4, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo'],               type:'II' },
  { name:'BmgBI',   recognitionSeq:'CACGTC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BmrI',    recognitionSeq:'ACTGG',  cutPos:5, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'IIS' },
  { name:'BmtI',    recognitionSeq:'GCTAGC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BpiI',    recognitionSeq:'GAAGAC', cutPos:8, cutPosBottom:12, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                        type:'IIS' },
  { name:'BseRI',   recognitionSeq:'GAGGAG', cutPos:16, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BseYI',   recognitionSeq:'CCCAGC', cutPos:10, cutPosBottom:14, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'BsiHKAI', recognitionSeq:'GWGCWC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BsiWI',   recognitionSeq:'CGTACG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BsmI',    recognitionSeq:'GAATGC', cutPos:7, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'IIS' },
  { name:'BsoBI',   recognitionSeq:'CYCGRG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BspEI',   recognitionSeq:'TCCGGA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BspHI',   recognitionSeq:'TCATGA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BsrBI',   recognitionSeq:'CCGCTC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BsrFI',   recognitionSeq:'RCCGGY', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BsrGI',   recognitionSeq:'TGTACA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BssHII',  recognitionSeq:'GCGCGC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'BssSI',   recognitionSeq:'CACGAG', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BstAPI',  recognitionSeq:'GCANNNNNTGC', cutPos:7, cutPosBottom:4, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                       type:'II' },
  { name:'BstBI',   recognitionSeq:'TTCGAA', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'BstNI',   recognitionSeq:'CCWGG',  cutPos:2, cutPosBottom:3, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'BstXI',   recognitionSeq:'CCANNNNNTGG', cutPos:8, cutPosBottom:3, overhang:'3prime', methylationSensitive:false, suppliers:['Thermo'],                    type:'IIS' },
  { name:'BstYI',   recognitionSeq:'RGATCY', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'BstZ17I', recognitionSeq:'GTATAC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'Csp6I',   recognitionSeq:'GTAC',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'DraI',    recognitionSeq:'TTTAAA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'DraIII',  recognitionSeq:'CACNNNGTG', cutPos:6, cutPosBottom:3, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                         type:'II' },
  { name:'DrdI',    recognitionSeq:'GACNNNNNNGTC', cutPos:7, cutPosBottom:5, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                      type:'II' },
  { name:'EagI',    recognitionSeq:'CGGCCG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'EarI',    recognitionSeq:'CTCTTC', cutPos:7, cutPosBottom:10, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                        type:'IIS' },
  { name:'EciI',    recognitionSeq:'GGCGGA', cutPos:17, cutPosBottom:15, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'Eco53kI', recognitionSeq:'GAGCTC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'EcoNI',   recognitionSeq:'CCTNNNNNAGG', cutPos:5, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                       type:'II' },
  { name:'EcoRI',   recognitionSeq:'GAATTC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'EcoRV',   recognitionSeq:'GATATC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'FauI',    recognitionSeq:'CCCGC',  cutPos:9, cutPosBottom:7, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'IIS' },
  { name:'Fnu4HI',  recognitionSeq:'GCNGC',  cutPos:2, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'FspI',    recognitionSeq:'TGCGCA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'HaeII',   recognitionSeq:'RGCGCY', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'HincII',  recognitionSeq:'GTYRAC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'HpaI',    recognitionSeq:'GTTAAC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'Hpy188I', recognitionSeq:'TCNGA',  cutPos:1, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'HpyCH4V', recognitionSeq:'TGCA',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'KasI',    recognitionSeq:'GGCGCC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MboII',   recognitionSeq:'GAAGA',  cutPos:13, cutPosBottom:12, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                       type:'IIS' },
  { name:'MfeI',    recognitionSeq:'CAATTG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MluCI',   recognitionSeq:'AATT',   cutPos:0, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MluI',    recognitionSeq:'ACGCGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'MscI',    recognitionSeq:'TGGCCA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MseI',    recognitionSeq:'TTAA',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MslI',    recognitionSeq:'CAYNNNNRTG', cutPos:5, cutPosBottom:5, overhang:'blunt', methylationSensitive:false, suppliers:['NEB'],                         type:'II' },
  { name:'MspA1I',  recognitionSeq:'CMGCKG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'MssI',    recognitionSeq:'GTTTAAAC', cutPos:4, cutPosBottom:4, overhang:'blunt', methylationSensitive:false, suppliers:['Thermo'],                        type:'II' },
  { name:'MunI',    recognitionSeq:'CAATTG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'NarI',    recognitionSeq:'GGCGCC', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB'],                            type:'II' },
  { name:'NcoI',    recognitionSeq:'CCATGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'NdeI',    recognitionSeq:'CATATG', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NgoMIV',  recognitionSeq:'GCCGGC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'NheI',    recognitionSeq:'GCTAGC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NlaIV',   recognitionSeq:'GGNNCC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'NotI',    recognitionSeq:'GCGGCCGC', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],        type:'II' },
  { name:'NruI',    recognitionSeq:'TCGCGA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NsiI',    recognitionSeq:'ATGCAT', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'NspI',    recognitionSeq:'RCATGY', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PacI',    recognitionSeq:'TTAATTAA', cutPos:3, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'PciI',    recognitionSeq:'ACATGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PflMI',   recognitionSeq:'CCANNNNNTGG', cutPos:7, cutPosBottom:4, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                       type:'II' },
  { name:'PmeI',    recognitionSeq:'GTTTAAAC', cutPos:4, cutPosBottom:4, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'PmlI',    recognitionSeq:'CACGTG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PpuMI',   recognitionSeq:'RGGWCCY', cutPos:2, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                           type:'II' },
  { name:'PsiI',    recognitionSeq:'TTATAA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PspOMI',  recognitionSeq:'GGGCCC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'PstI',    recognitionSeq:'CTGCAG', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega','Takara'], type:'II' },
  { name:'PvuI',    recognitionSeq:'CGATCG', cutPos:4, cutPosBottom:2, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'PvuII',   recognitionSeq:'CAGCTG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'RsrII',   recognitionSeq:'CGGWCCG', cutPos:2, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                           type:'II' },
  { name:'SacI',    recognitionSeq:'GAGCTC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SacII',   recognitionSeq:'CCGCGG', cutPos:4, cutPosBottom:2, overhang:'3prime', methylationSensitive:true,  suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'SalI',    recognitionSeq:'GTCGAC', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SapI',    recognitionSeq:'GCTCTTC', cutPos:8, cutPosBottom:11, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'IIS' },
  { name:'ScaI',    recognitionSeq:'AGTACT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'SfaNI',   recognitionSeq:'GCATC',  cutPos:9, cutPosBottom:6, overhang:'3prime', methylationSensitive:false, suppliers:['NEB'],                            type:'IIS' },
  { name:'SfcI',    recognitionSeq:'CTRYAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'SfoI',    recognitionSeq:'GGCGCC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'SgrAI',   recognitionSeq:'CRCCGGYG', cutPos:2, cutPosBottom:6, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                          type:'II' },
  { name:'SmaI',    recognitionSeq:'CCCGGG', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SmiI',    recognitionSeq:'ATTTAAAT', cutPos:4, cutPosBottom:4, overhang:'blunt', methylationSensitive:false, suppliers:['Thermo'],                        type:'II' },
  { name:'SmlI',    recognitionSeq:'CTYRAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'SnaBI',   recognitionSeq:'TACGTA', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'SpeI',    recognitionSeq:'ACTAGT', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'SphI',    recognitionSeq:'GCATGC', cutPos:5, cutPosBottom:1, overhang:'3prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'SrfI',    recognitionSeq:'GCCCGGGC', cutPos:4, cutPosBottom:4, overhang:'blunt', methylationSensitive:false, suppliers:['Stratagene'],                    type:'II' },
  { name:'SspI',    recognitionSeq:'AATATT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'StuI',    recognitionSeq:'AGGCCT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB','Thermo'],                   type:'II' },
  { name:'StyI',    recognitionSeq:'CCWWGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'SwaI',    recognitionSeq:'ATTTAAAT', cutPos:4, cutPosBottom:4, overhang:'blunt', methylationSensitive:false, suppliers:['NEB'],                           type:'II' },
  { name:'TaiI',    recognitionSeq:'ACGT',   cutPos:4, cutPosBottom:0, overhang:'3prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'TaqI',    recognitionSeq:'TCGA',   cutPos:1, cutPosBottom:3, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'TliI',    recognitionSeq:'CTCGAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'Tth111I', recognitionSeq:'GACNNNGTC', cutPos:4, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                         type:'II' },
  { name:'VspI',    recognitionSeq:'ATTAAT', cutPos:2, cutPosBottom:4, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'XbaI',    recognitionSeq:'TCTAGA', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:true,  suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'XhoI',    recognitionSeq:'CTCGAG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB','Thermo','Promega'],          type:'II' },
  { name:'XhoII',   recognitionSeq:'RGATCY', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'XmaI',    recognitionSeq:'CCCGGG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'XmaIII',  recognitionSeq:'CGGCCG', cutPos:1, cutPosBottom:5, overhang:'5prime', methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
  { name:'XmnI',    recognitionSeq:'GAANNNNTTC', cutPos:5, cutPosBottom:5, overhang:'blunt', methylationSensitive:false, suppliers:['NEB'],                         type:'II' },
  { name:'ZraI',    recognitionSeq:'GACGTC', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['NEB'],                            type:'II' },
  { name:'ZrmI',    recognitionSeq:'AGTACT', cutPos:3, cutPosBottom:3, overhang:'blunt',  methylationSensitive:false, suppliers:['Thermo'],                         type:'II' },
];

// Deduplicate by name (keep first occurrence)
const seen = new Set<string>();
export const ENZYME_DB: RestrictionEnzyme[] = REBASE_ENZYMES.filter(e => {
  if (seen.has(e.name)) return false;
  seen.add(e.name);
  return true;
});

export const ALL_SUPPLIERS = ['NEB', 'Thermo', 'Promega', 'Takara', 'Stratagene'] as const;
